### PR TITLE
added trained ae (tensorflow) model from the old repository

### PR DESCRIPTION
**Pull request by JohanvandenHeuvel**
model taken from:
 https://github.com/Philoso-Fish/Benchmarkin_Counterfactual_Examples/blob/892f0d320a741a81fe9368ba56cd7cb47eb84ccd/CF_Models/cem_ml/AE_models/Saved_Models/ae_tf_adult_full.h5

- There is also a model for "adult_reduced". 
- Should a model.py and train.py be available for all models?

### CODE REVIEW

**Comment by indyfree** [comment]
> There is also a model for "adult_reduced".

I am not sure which one we actually took, I think @Philoso-Fish has the best overview there

> Should a model.py and train.py be available for all models?

Ideally yes. We could include e.g. `training/adult/ae.py`.
Also would be nice to do it for the other models then aswell

**Comment by Philoso-Fish** [comment]
> > There is also a model for "adult_reduced".
> 
> I am not sure which one we actually took, I think @Philoso-Fish has the best overview there

I think the reduced version refers to the adult dataset with lesser features (e.g., only 1 column for binary categorical features kept instead of 2), which is an aftereffect of the same problem for the ML model.


> > Should a model.py and train.py be available for all models?
> 
> Ideally yes. We could include e.g. `training/adult/ae.py`.
> Also would be nice to do it for the other models then aswell

You mean, keeping the training scripts for our ML models, too?
For AEs this would make sense, since these should be fitted to arbitrary datasets and used features/feature_order, etc., and they are part of the inner functionality of a recourse method.

**Comment by JohanvandenHeuvel** [comment]
> > > Should a model.py and train.py be available for all models?
> > 
> > 
> > Ideally yes. We could include e.g. `training/adult/ae.py`.
> > Also would be nice to do it for the other models then aswell
> 
> You mean, keeping the training scripts for our ML models, too?
> For AEs this would make sense, since these should be fitted to arbitrary datasets and used features/feature_order, etc., and they are part of the inner functionality of a recourse method.

Do you have code you can add to the branch? I guess it's fine if it's messy, I can clean it up a bit.

**Comment by Philoso-Fish** [comment]
> Do you have code you can add to the branch? I guess it's fine if it's messy, I can clean it up a bit.

I think model structure and code are in CF_Models/cem_ml/AE_models/AE
Martin implemented all AE models 😅

**Comment by JohanvandenHeuvel** [comment]
The training files depend quite strongly on the data, which we don't include in this repository. So I think it's better for now if we include the model definitions (.json files) and keep it at that.

**Comment by Philoso-Fish** [comment]
> The training files depend quite strongly on the data, which we don't include in this repository. So I think it's better for now if we include the model definitions (.json files) and keep it at that.

I'm not sure if I understood the purpose of the json file. It contains the model structure? Doesn't the saved tensorflow model contain exactly the same information? We're doing the same for the ann model and do not export a separate json file.

These dependencies are all over the old project, that's the reason why we're rewriting everything to use it as python package.
I don't think that we can copy/ paste any bigger parts.

**Pull request merged**
